repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-yaml
            exclude: "^$"
    - repo: local
      hooks:
          - id: yaml-validator
            name: Validate YAML files
            entry: python yaml_validator.py
            args: []
            language: python
            types: [yaml]
            files: test.yaml
