---

type: seq
sequence:
  - type: map
    mapping:
      code:
        type: str
        pattern: "^[A-Z]{2}[0-9]{3}$"
        required: true
        unique: true
      description:
        type: str
        required: true
        func: validate_titlecase
      location:
        type: str
        pattern: "^[a-z]+(_[a-z]+)*$"
        enum:
          - last_stand
          - final_countdown
        required: true
      solution:
        type: str
        required: false
