rules:
  code:
    required: true
    type: int
    regex: "^[0-9]*$"

  description:
    required: true
    type: str
    regex: "^[a-zA-Z ]*$"
    snake_case: false
    title_case: true

  location:
    type: str
    regex: "^[0-9]{4}-[01][0-9]-[0-3][0-9]$"

  solution:
    type: str
    quotes: '"'

  dict_keys:
    keys:
      - code
      - description
      - location
      - solution
